# Movie Recommendation System

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

ModuleNotFoundError: No module named 'sklearn'

In [2]:
!pip install scikit-learn

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [3]:
import sys
!{sys.executable} -m pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\spoorthy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (2.4.3)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ----------------------- ---------------- 4.7/8.1 MB 26.8 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 22.9 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 20.0 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   -- ------------------------------------- 2.1/37.3 MB 10.1 MB/s eta 0:00:04
   --- ------------------------------------ 3.1/37.3 MB 7.4 MB/s eta 0:00:05
   ---- ----------------------------------- 4.2/37.3 MB 6.5 MB/s eta 0:00:06
   ----- ---------------------------------- 5.2/37.3 MB 6.1 MB/s eta 0:00:06
   ----- ---------------------------------- 5.5/37.3 MB 5.7 MB/s eta 0:00:06
   ------ --------------------------------- 5.8/37.3 MB 5.0 MB/s eta 0:00:07
   ------ --------------------------------- 6.0/37.3 MB 4.2 MB/s eta 0:00:08
   ------ --------------------------------- 6.3/37.3 MB 3.9 MB/s eta 0:00:08
   ------- -------------------------------- 6.8/37.3 MB 3.6 MB/s eta 0:00:09
   ------- -------------------------------- 7.3/37.3 MB 3.6 MB/s eta 0:00:09
   -------- ------------------------------- 7.6/37.3 MB 3.4 MB/s eta 0:00:09
   -------- ------------------------------- 7.9/37.3 MB 3.2 MB/s eta 0:00:10
   -------- ------------------------------- 8.1/37.3 MB 3.0 MB/s eta 0:00:10
   -------- ------------------------------- 8.1/37.3 MB 3.0 MB/s eta 0:00:10
   -------- ------------------------------- 8.1/37.3 MB 3.0 MB/s eta 0:00:10
   -------- ------------------------------- 8.4/37.3 MB 2.5 MB/s eta 0:00:12
   -------- ------------------------------- 8.4/37.3 MB 2.5 MB/s eta 0:00:12
   --------- ------------------------------ 8.7/37.3 MB 2.3 MB/s eta 0:00:13
   --------- ------------------------------ 8.9/37.3 MB 2.2 MB/s eta 0:00:13
   --------- ------------------------------ 8.9/37.3 MB 2.2 MB/s eta 0:00:13
   --------- ------------------------------ 9.2/37.3 MB 2.1 MB/s eta 0:00:14
   --------- ------------------------------ 9.2/37.3 MB 2.1 MB/s eta 0:00:14
   ---------- ----------------------------- 9.4/37.3 MB 2.0 MB/s eta 0:00:15
   ---------- ----------------------------- 9.7/37.3 MB 1.9 MB/s eta 0:00:15
   ---------- ----------------------------- 10.0/37.3 MB 1.9 MB/s eta 0:00:15
   ---------- ----------------------------- 10.2/37.3 MB 1.9 MB/s eta 0:00:15
   ----------- ---------------------------- 10.7/37.3 MB 1.9 MB/s eta 0:00:15
   ------------ --------------------------- 11.5/37.3 MB 1.9 MB/s eta 0:00:14
   ------------ --------------------------- 12.1/37.3 MB 2.0 MB/s eta 0:00:13
   ------------- -------------------------- 12.6/37.3 MB 2.0 MB/s eta 0:00:13
   -------------- ------------------------- 13.1/37.3 MB 2.0 MB/s eta 0:00:13
   -------------- ------------------------- 13.6/37.3 MB 2.0 MB/s eta 0:00:12
   -------------- ------------------------- 13.9/37.3 MB 2.0 MB/s eta 0:00:12
   -------------- ------------------------- 13.9/37.3 MB 2.0 MB/s eta 0:00:12
   --------------- ------------------------ 14.2/37.3 MB 1.9 MB/s eta 0:00:12
   --------------- ------------------------ 14.7/37.3 MB 1.9 MB/s eta 0:00:12
   ---------------- ----------------------- 14.9/37.3 MB 1.9 MB/s eta 0:00:12
   ---------------- ----------------------- 15.5/37.3 MB 1.9 MB/s eta 0:00:12
   ----------------- ---------------------- 16.0/37.3 MB 1.9 MB/s eta 0:00:12
   ----------------- ---------------------- 16.3/37.3 MB 1.9 MB/s eta 0:00:11
   ----------------- ---------------------- 16.5/37.3 MB 1.9 MB/s eta 0:00:11
   ----------------- ---------------------- 16.8/37.3 MB 1.9 MB/s eta 0:00:11
   ----------------- ---------------------- 16.8/37.3 MB 1.9 MB/s eta 0:00:11
   ------------------ --------------------- 17.0/37.3 MB 1.8 MB/s eta 0:00:11
   ------------------ --------------------- 17.3/37.3 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 17.8/37.3 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 18.4/37.3 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 19.1/37.3 MB 1.9 MB/s eta 0:00:10
   --------------------- ------------------ 19.7/37.3 MB 1.9 MB/s eta 0:00:10
   --------------------- ------------------ 20.4/37.3 MB 1.9 MB/s eta 0:00:09
   ----------------------- ---------------- 21.5/37.3 MB 2.0 MB/s eta 0:00:08
   ------------------------ --------------- 22.5/37.3 MB 2.0 MB/s eta 0:00:08
   ------------------------- -------------- 23.9/37.3 MB 2.1 MB/s eta 0:00:07
   -------------------------- ------------- 25.2/37.3 MB 2.2 MB/s eta 0:00:06
   ---------------------------- ----------- 26.5/37.3 MB 2.3 MB/s eta 0:00:05
   ----------------------------- ---------- 27.8/37.3 MB 2.3 MB/s eta 0:00:05
   ------------------------------ --------- 28.3/37.3 MB 2.3 MB/s eta 0:00:04
   ------------------------------ --------- 28.6/37.3 MB 2.3 MB/s eta 0:00:04
   ------------------------------ --------- 28.8/37.3 MB 2.3 MB/s eta 0:00:04
   ------------------------------- -------- 29.1/37.3 MB 2.3 MB/s eta 0:00:04
   ------------------------------- -------- 29.4/37.3 MB 2.3 MB/s eta 0:00:04
   ------------------------------- -------- 29.6/37.3 MB 2.2 MB/s eta 0:00:04
   -------------------------------- ------- 29.9/37.3 MB 2.2 MB/s eta 0:00:04
   -------------------------------- ------- 30.1/37.3 MB 2.2 MB/s eta 0:00:04
   -------------------------------- ------- 30.4/37.3 MB 2.2 MB/s eta 0:00:04
   -------------------------------- ------- 30.4/37.3 MB 2.2 MB/s eta 0:00:04
   -------------------------------- ------- 30.7/37.3 MB 2.2 MB/s eta 0:00:04
   --------------------------------- ------ 30.9/37.3 MB 2.1 MB/s eta 0:00:03
   --------------------------------- ------ 31.2/37.3 MB 2.1 MB/s eta 0:00:03
   --------------------------------- ------ 31.2/37.3 MB 2.1 MB/s eta 0:00:03
   --------------------------------- ------ 31.5/37.3 MB 2.1 MB/s eta 0:00:03
   ---------------------------------- ----- 31.7/37.3 MB 2.1 MB/s eta 0:00:03
   ---------------------------------- ----- 32.0/37.3 MB 2.1 MB/s eta 0:00:03
   ---------------------------------- ----- 32.2/37.3 MB 2.1 MB/s eta 0:00:03
   ----------------------------------- ---- 32.8/37.3 MB 2.0 MB/s eta 0:00:03
   ----------------------------------- ---- 33.0/37.3 MB 2.0 MB/s eta 0:00:03
   ----------------------------------- ---- 33.3/37.3 MB 2.0 MB/s eta 0:00:02
   ----------------------------------- ---- 33.6/37.3 MB 2.0 MB/s eta 0:00:02
   ------------------------------------ --- 33.8/37.3 MB 2.0 MB/s eta 0:00:02
   ------------------------------------ --- 34.1/37.3 MB 2.0 MB/s eta 0:00:02
   ------------------------------------ --- 34.1/37.3 MB 2.0 MB/s eta 0:00:02
   ------------------------------------ --- 34.3/37.3 MB 2.0 MB/s eta 0:00:02
   ------------------------------------ --- 34.3/37.3 MB 2.0 MB/s eta 0:00:02
   ------------------------------------- -- 34.6/37.3 MB 1.9 MB/s eta 0:00:02
   ------------------------------------- -- 34.9/37.3 MB 1.9 MB/s eta 0:00:02
   ------------------------------------- -- 35.4/37.3 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 35.7/37.3 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 35.9/37.3 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 36.2/37.3 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  36.4/37.3 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  37.0/37.3 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 1.9 MB/s  0:00:19
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\spoorthy\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
df = pd.read_csv("movies.csv")
df.head()

,title,genre,description
0,Avatar,Action Sci-Fi,A marine on an alien planet becomes part of a ...
1,Titanic,Romance Drama,A love story unfolds on the ill-fated Titanic ...
2,The Avengers,Action Superhero,Earth's mightiest heroes unite to stop a globa...
3,Iron Man,Action Superhero,A billionaire engineer builds a powered suit a...
4,Captain America: The First Avenger,Action Superhero,A brave man becomes a super soldier during Wor...

In [6]:
df["features"] = df["genre"] + " " + df["description"]
df[["title", "features"]].head()

,title,features
0,Avatar,Action Sci-Fi A marine on an alien planet beco...
1,Titanic,Romance Drama A love story unfolds on the ill-...
2,The Avengers,Action Superhero Earth's mightiest heroes unit...
3,Iron Man,Action Superhero A billionaire engineer builds...
4,Captain America: The First Avenger,Action Superhero A brave man becomes a super s...

In [7]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["features"])

In [8]:
similarity = cosine_similarity(count_matrix)
similarity

array([[1.        , 0.07537784, 0.07905694, 0.23717082, 0.15075567,
        0.20801257, 0.20801257, 0.15811388, 0.08333333, 0.07905694,
        0.2773501 , 0.51639778, 0.07905694, 0.13867505, 0.13363062,
        0.        , 0.05455447, 0.        , 0.        , 0.        ],
       [0.07537784, 1.        , 0.        , 0.        , 0.        ,
        0.0836242 , 0.        , 0.09534626, 0.10050378, 0.        ,
        0.0836242 , 0.        , 0.38138504, 0.1672484 , 0.16116459,
        0.08703883, 0.19738551, 0.09534626, 0.        , 0.        ],
       [0.07905694, 0.        , 1.        , 0.2       , 0.19069252,
        0.26311741, 0.0877058 , 0.1       , 0.10540926, 0.1       ,
        0.0877058 , 0.16329932, 0.        , 0.        , 0.        ,
        0.09128709, 0.13801311, 0.        , 0.        , 0.        ],
       [0.23717082, 0.        , 0.2       , 1.        , 0.28603878,
        0.1754116 , 0.0877058 , 0.        , 0.10540926, 0.1       ,
        0.0877058 , 0.24494897, 0.1       , 0.0877058 , 0.08451543,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.15075567, 0.        , 0.19069252, 0.28603878, 1.        ,
        0.0836242 , 0.        , 0.        , 0.10050378, 0.09534626,
        0.0836242 , 0.23354968, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.20801257, 0.0836242 , 0.26311741, 0.1754116 , 0.0836242 ,
        1.        , 0.15384615, 0.0877058 , 0.18490007, 0.26311741,
        0.23076923, 0.35805744, 0.0877058 , 0.07692308, 0.22237479,
        0.16012815, 0.30261377, 0.0877058 , 0.        , 0.        ],
       [0.20801257, 0.        , 0.0877058 , 0.0877058 , 0.        ,
        0.15384615, 1.        , 0.26311741, 0.        , 0.        ,
        0.15384615, 0.28644595, 0.0877058 , 0.15384615, 0.07412493,
        0.08006408, 0.12104551, 0.        , 0.10482848, 0.        ],
       [0.15811388, 0.09534626, 0.1       , 0.        , 0.        ,
        0.0877058 , 0.26311741, 1.        , 0.        , 0.        ,
        0.26311741, 0.24494897, 0.1       , 0.        , 0.        ,
        0.18257419, 0.13801311, 0.        , 0.        , 0.        ],
       [0.08333333, 0.10050378, 0.10540926, 0.10540926, 0.10050378,
        0.18490007, 0.        , 0.        , 1.        , 0.10540926,
        0.18490007, 0.0860663 , 0.        , 0.09245003, 0.17817416,
        0.09622504, 0.14547859, 0.10540926, 0.        , 0.        ],
       [0.07905694, 0.        , 0.1       , 0.1       , 0.09534626,
        0.26311741, 0.        , 0.        , 0.10540926, 1.        ,
        0.0877058 , 0.08164966, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.10540926],
       [0.2773501 , 0.0836242 , 0.0877058 , 0.0877058 , 0.0836242 ,
        0.23076923, 0.15384615, 0.26311741, 0.18490007, 0.0877058 ,
        1.        , 0.28644595, 0.        , 0.        , 0.14824986,
        0.08006408, 0.18156826, 0.0877058 , 0.        , 0.        ],
       [0.51639778, 0.        , 0.16329932, 0.24494897, 0.23354968,
        0.35805744, 0.28644595, 0.24494897, 0.0860663 , 0.08164966,
        0.28644595, 1.        , 0.08164966, 0.07161149, 0.13801311,
        0.0745356 , 0.16903085, 0.        , 0.        , 0.        ],
       [0.07905694, 0.38138504, 0.        , 0.1       , 0.        ,
        0.0877058 , 0.0877058 , 0.1       , 0.        , 0.        ,
        0.        , 0.08164966, 1.        , 0.26311741, 0.16903085,
        0.        , 0.06900656, 0.        , 0.        , 0.        ],
       [0.13867505, 0.1672484 , 0.        , 0.0877058 , 0.        ,
        0.07692308, 0.15384615, 0.        , 0.09245003, 0.        ,
        0.        , 0.07161149, 0.26311741, 1.        , 0.22237479,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.13363062, 0.16116459, 0.        , 0.08451543, 0.        ,
        0.22237479, 0.07412493, 0.        , 0.17817416, 0.        ,
        0.14824986, 0.13801311, 0.16903085, 0.22237479, 1.        ,
        0.15430335, 0.40824829, 0.16903085, 0.        , 0.08908708],
       [0.        , 0.08703883, 0.09128709, 0.        , 0.        ,
        0.16012815, 0.08006408, 0.18257419, 0.09622504, 0.        ,
        0.08006408, 0.0745356 , 0.        , 0.        , 0.15430335,
        1.        , 0.31497039, 0.36514837, 0.        , 0.        ],
       [0.05455447, 0.19738551, 0.13801311, 0.        , 0.        ,
        0.30261377, 0.12104551, 0.13801311, 0.14547859, 0.        ,
        0.18156826, 0.16903085, 0.06900656, 0.        , 0.40824829,
        0.31497039, 1.        , 0.27602622, 0.        , 0.14547859],
       [0.        , 0.09534626, 0.        , 0.        , 0.        ,
        0.0877058 , 0.        , 0.        , 0.10540926, 0.        ,
        0.0877058 , 0.        , 0.        , 0.        , 0.16903085,
        0.36514837, 0.27602622, 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.10482848, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.12598816],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.10540926,
        0.        , 0.        , 0.        , 0.        , 0.08908708,
        0.        , 0.14547859, 0.        , 0.12598816, 1.        ]])

In [9]:
def recommend_movie(movie_name):
    movie_name = movie_name.lower()
    
    matching_movies = df[df["title"].str.lower() == movie_name]
    
    if matching_movies.empty:
        return "Movie not found in dataset."
    
    movie_index = matching_movies.index[0]
    similarity_scores = list(enumerate(similarity[movie_index]))
    sorted_movies = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    
    recommendations = []
    for movie in sorted_movies[1:6]:
        recommendations.append(df.iloc[movie[0]]["title"])
    
    return recommendations

In [10]:
recommend_movie("Avatar")

['John Carter', 'Guardians of the Galaxy', 'Iron Man', 'Thor', 'Inception']

In [11]:
recommend_movie("Titanic")

['The Notebook', 'Coco', 'La La Land', 'Frozen', 'The Dark Knight']

In [12]:
recommend_movie("Frozen")

['Coco', 'Thor', 'La La Land', 'The Dark Knight', 'The Notebook']

## Conclusion

This project recommends similar movies based on genre and description.

Key points:
1. Loaded and processed movie data using Python and Pandas.
2. Combined text features like genre and description.
3. Used CountVectorizer to convert text into numbers.
4. Applied cosine similarity to find similar movies.
5. Built a recommendation function to suggest movies.